"""
Django settings for cms project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from django.templatetags.static import static


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_ROOT = BASE_DIR / "staticfiles_collected"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z9%#w@3^tu2u@n1p$y7n-__an=5o1it+h0+$)qk$0*_h5)@%sq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Settings for running behind a reverse proxy
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

DJANGO_ADMIN_LOGS_ENABLED = True
# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold_markdown',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'blog',
    'django_cleanup.apps.CleanupConfig',
    'django_admin_logs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:8080",
    'http://localhost:8080',
]

CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1', 'http://localhost', "http://192.168.0.103"]

INTERNAL_IPS = [
    '127.0.0.1',
]

ROOT_URLCONF = 'cms.urls'



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'cms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # Указва, че ползваме MySQL
        'NAME': 'test_pgknma',  # Например: my_custom_blog
        'USER': 'root',  # Например: root
        'PASSWORD': '',
        'HOST': 'localhost',  # Или IP адреса на сървъра
        'PORT': '3306',  # Стандартният порт за MySQL

        # Задължително кодиране за кирилица
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'bg'

TIME_ZONE = 'EET'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
}

# CORS settings for debugging - CAN BE TIGHTENED LATER
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
# CORS_ALLOW_HEADERS = [
#     'Authorization',
#     'Content-Type',
# ]

MEDIA_URL = '/files/'
MEDIA_ROOT = BASE_DIR / 'files'

UNFOLD = {
    "SITE_DROPDOWN": [
            {
                "icon": "diamond",
                "title": ("Начална страница"),
                "link": "http://192.168.0.103/",
            },
            {
                "icon": "folder",
                "title": ("Официален сайт"),
                "link": "https://pgknma.com/",
            }
        ],
    "SITE_TITLE": "Админ панел - ПГКНМА",
    "SITE_HEADER": "CMS ПГКНМА Блог",
    "SITE_SUBHEADER": "Система за управление на съдържанието",
    "SITE_ICON": lambda request: static("images/logo.png"),
    "SITE_SYMBOL": "school", # A generic symbol from Google Material Icons
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": False,
    "BORDER_RADIUS": "6px",
    "SIDEBAR": {
        "navigation": [
            {
                "items":[
                    {
                        "title": "Начало",
                        "link": "/admin/",
                        "icon": "home",
                    },
                    {
                        "title": "Изпратени контактни формуляри",
                        "link": "/admin/blog/contactsubmission/",
                        "icon": "mail",
                    },
                ],
            },
            {
                "separator": True,
                "title": "Управление на съдържанието",
                "items": [
                    {
                        "title": "Публикации",
                        "link": "/admin/blog/posts/",
                        "icon": "article",
                    },
                    {
                        "title": "Категории",
                        "link": "/admin/blog/category/",
                        "icon": "label",
                    },
                    {
                        "title": "Снимки към публикации",
                        "link": "/admin/blog/postimage/",
                        "icon": "image",
                    },
                    {
                        "title": "Файлове към публикации",
                        "link": "/admin/blog/postdocument/",
                        "icon": "book",
                    },
                    {
                        "title": "Събития",
                        "link": "/admin/blog/event/",
                        "icon": "event",
                    },
                    {
                        "title": "Известия",
                        "link": "/admin/blog/notification/",
                        "icon": "notifications",
                    },
                ],
            },
            {

                "separator": True,
                "title": "Ангажираност на потребителите",
                "items": [
                    {
                        "title": "Въпроси за анкети",
                        "link": "/admin/blog/pollquestion/",
                        "icon": "poll",
                    },
                    {
                        "title": "Отговори на анкети",
                        "link": "/admin/blog/pollanswer/",
                        "icon": "how_to_vote",
                    },
                    {
                        "title": "Предложения за песни",
                        "link": "/admin/blog/bellsongsuggestion/",
                        "icon": "music_note",
                    },
                    {
                        "title": "Меме на седмицата",
                        "link": "/admin/blog/memeofweek/",
                        "icon": "sentiment_very_satisfied",
                    },
                    {
                        "title": "Коментари",
                        "link": "/admin/blog/comments/",
                        "icon": "comment",
                    },
                ],
            },
            {
                "separator": True,
                "collapsible": True,
                "title": "Администрация",
                "items": [
                    {
                        "title": "Настройки на сайта",
                        "link": "/admin/blog/sitesettings/",
                        "icon": "settings",
                    },
                    {
                        "title": "Регистър с промени",
                        "link": "/admin/blog/changelog/add/",
                        "icon": "settings",
                    },
                    {
                        "title": "Политики за поверителност",
                        "link": "/admin/blog/privacypolicy/",
                        "icon": "privacy_tip",
                    },
                    {
                        "title": "Условия за ползване",
                        "link": "/admin/blog/termsofservice/",
                        "icon": "gavel",
                    },
                    {
                        "title": "Записи на съгласие за бисквитки",
                        "link": "/admin/blog/consentrecord/",
                        "icon": "cookie",
                    },
                    {
                        "title": "Журнал на действията",
                        "link": "/admin/admin/logentry/",
                        "icon": "history",
                    },
                ],
            },
            {
                "collapsible": True,
                "title": "Аутентикация и оторизация ",
                "items": [
                    {
                        "title": "Потребители",
                        "link": "/admin/auth/user/",
                        "icon": "person",
                    },
                    {
                        "title": "Групи",
                        "link": "/admin/auth/group/",
                        "icon": "groups",
                    },
                ],
            },
        ],
    },
}