# Generated by Django 6.0 on 2025-12-04 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'permissions': [('view_only_posts', 'View only users posts'), ('can_view_all_posts', 'Can view all posts'), ('can_view_all_pnp_posts', 'Can view all post if they not published')]},
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
