# Generated by Django 6.0 on 2025-12-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_posts_options_alter_posts_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'permissions': [('view_only_posts', 'View only users posts'), ('can_view_all_posts', 'Can view all posts'), ('can_view_all_pnp_posts', 'Can view all post if they not published')], 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
    ]
