# Generated by Django 6.0 on 2025-12-04 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options_alter_posts_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permissions',
        ),
    ]
