# Generated by Django 6.0 on 2025-12-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'permissions': [('view_only_posts', 'View only users posts'), ('can_view_all_posts', 'Can view all posts'), ('can_view_all_pnp_posts', 'Can view all post if they not published'), ('can_allow_posts', 'Can allow posts')], 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AddField(
            model_name='posts',
            name='allowed',
            field=models.BooleanField(default=False),
        ),
    ]
