# Generated by Django 6.0 on 2025-12-04 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_posts_options_posts_allowed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'permissions': [('view_only_posts', 'View only users posts'), ('can_view_all_posts', 'Can view all posts'), ('can_view_all_pnp_posts', 'Can view all post if they not published'), ('can_allow_posts', 'Can allow posts'), ('can_edit_users_post', 'Can edit users posts')], 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
    ]
