# Generated by Django 6.0 on 2025-12-05 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_posts_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, choices=[('8a', '8 А'), ('8b', '8 Б'), ('8v', '8 В'), ('9a', '9 А'), ('9b', '9 Б'), ('9v', '9 В'), ('10a', '10 А'), ('10b', '10 Б'), ('10v', '10 В'), ('11a', '11 А'), ('11b', '11 Б'), ('11v', '11 В'), ('12a', '12 А'), ('12b', '12 Б')], max_length=5, null=True, verbose_name='Клас')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
