# Generated by Django 6.0 on 2025-12-05 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('consent_status', models.CharField(choices=[('INFORMED', 'Информиран (Необходими)'), ('ACCEPTED', 'Приел'), ('REJECTED', 'Отказал')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('policy_version', models.CharField(default='v1.0', max_length=10)),
                ('analytical_accepted', models.BooleanField(default=False)),
                ('marketing_accepted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
