# Generated by Django 6.0 on 2025-12-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_cookie_consentrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('8a', '8 А'), ('8b', '8 Б'), ('8v', '8 В'), ('9a', '9 А'), ('9b', '9 Б'), ('9v', '9 В'), ('10a', '10 А'), ('10b', '10 Б'), ('10v', '10 В'), ('11a', '11 А'), ('11b', '11 Б'), ('11v', '11 В'), ('12a', '12 А'), ('12b', '12 Б'), ('teacher', 'TEACHER')], max_length=10)),
                ('monday', models.CharField(max_length=255)),
                ('tuesday', models.CharField(max_length=255)),
                ('wednesday', models.CharField(max_length=255)),
                ('thursday', models.CharField(max_length=255)),
                ('friday', models.CharField(max_length=255)),
            ],
        ),
    ]
