# Generated by Django 6.0 on 2025-12-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='program',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='program',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='program',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='program',
            name='wednesday',
        ),
    ]
