# Generated by Django 6.0 on 2025-12-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_program_friday_remove_program_monday_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program',
        ),
    ]
