# Generated by Django 6.0 on 2025-12-17 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_delete_program'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PollQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заглавие')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаглавие')),
                ('code', models.TextField(verbose_name='Код')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създаден на')),
            ],
            options={
                'verbose_name': 'Въпрос за анкета',
                'verbose_name_plural': 'Въпроси за анкети',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст на опция')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правилен отговор')),
                ('key', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, verbose_name='Ключ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='blog.pollquestion', verbose_name='Въпрос')),
            ],
            options={
                'verbose_name': 'Опция за анкета',
                'verbose_name_plural': 'Опции за анкети',
                'ordering': ['key'],
                'unique_together': {('question', 'key')},
            },
        ),
        migrations.CreateModel(
            name='PollAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отговорено на')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Потребител')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.polloption', verbose_name='Избрана опция')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.pollquestion', verbose_name='Въпрос')),
            ],
            options={
                'verbose_name': 'Отговор на анкета',
                'verbose_name_plural': 'Отговори на анкети',
                'ordering': ['-created_at'],
            },
        ),
    ]
