# Generated by Django 6.0 on 2025-12-17 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_pollquestion_polloption_pollanswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Име')),
                ('email', models.EmailField(max_length=254, verbose_name='Имейл')),
                ('message', models.TextField(verbose_name='Съобщение')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Изпратено на')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Потребител')),
            ],
            options={
                'verbose_name': 'Изпратен контактен формуляр',
                'verbose_name_plural': 'Изпратени контактни формуляри',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
