# Generated by Django 6.0 on 2025-12-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_contactsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст на известието')),
                ('enabled', models.BooleanField(default=True, verbose_name='Активирано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създадено на')),
            ],
            options={
                'verbose_name': 'Известие',
                'verbose_name_plural': 'Известия',
                'ordering': ['-created_at'],
            },
        ),
    ]
