# Generated by Django 6.0 on 2025-12-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_notification_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст на известието'),
        ),
    ]
