# Generated by Django 6.0 on 2025-12-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_termsofuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заглавие')),
                ('start_datetime', models.DateTimeField(verbose_name='Начална дата и час')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Крайна дата и час (по избор)')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('attendees_text', models.CharField(max_length=255, verbose_name='Участници (текст)')),
                ('published', models.BooleanField(default=True, verbose_name='Публикувано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създадено на')),
            ],
            options={
                'verbose_name': 'Събитие',
                'verbose_name_plural': 'Събития',
                'ordering': ['start_datetime'],
            },
        ),
    ]
