# Generated by Django 6.0 on 2025-12-19 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termsofuser',
            options={'verbose_name': 'Условие за ползване', 'verbose_name_plural': 'Условия за ползване'},
        ),
    ]
