# Generated by Django 6.0 on 2025-12-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_termsofuser_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TermsOfUser',
            new_name='TermsOfService',
        ),
    ]
