# Generated by Django 6.0 on 2025-12-20 19:13

import blog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_rename_termsofuser_to_termsofservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=blog.models.post_media_upload_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.posts')),
            ],
            options={
                'verbose_name': 'Снимка към публикация',
                'verbose_name_plural': 'Снимки към публикации',
            },
        ),
    ]
