# Generated by Django 6.0 on 2025-12-21 09:43

import blog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_postimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='class_name',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=blog.models.post_gallery_upload_path),
        ),
        migrations.AlterField(
            model_name='posts',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.post_banner_upload_path),
        ),
        migrations.CreateModel(
            name='BellSongSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заглавие на песента')),
                ('link', models.URLField(max_length=2048, verbose_name='Линк към песента')),
                ('slot', models.CharField(choices=[('start_class', 'Начало на час'), ('end_class', 'Край на час'), ('before_lunch', 'Преди голямо междучасие'), ('after_lunch', 'След голямо междучасие'), ('morning', 'Сутрешен звънец'), ('special', 'Специален повод')], default='morning', max_length=20, verbose_name='Кога да звучи')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Бележка')),
                ('status', models.CharField(choices=[('pending', 'Чакащо одобрение'), ('approved', 'Одобрено'), ('rejected', 'Отхвърлено')], default='pending', max_length=10, verbose_name='Статус')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Изпратено на')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Потребител')),
            ],
            options={
                'verbose_name': 'Предложение за песен за звънец',
                'verbose_name_plural': 'Предложения за песни за звънец',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.DeleteModel(
            name='BellRequest',
        ),
    ]
