# Generated by Django 6.0 on 2025-12-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_privacypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='bellsongsuggestion',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Гласове'),
        ),
    ]
