# Generated by Django 6.0 on 2025-12-21 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_bellsongsuggestion_votes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bellsongsuggestion',
            name='voted_by',
            field=models.ManyToManyField(blank=True, related_name='voted_songs', to=settings.AUTH_USER_MODEL, verbose_name='Гласували потребители'),
        ),
    ]
