# Generated by Django 6.0 on 2025-12-22 19:56

import blog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_bellsongsuggestion_voted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memeofweek',
            options={'ordering': ['-created_at'], 'verbose_name': 'Меме на седмицата', 'verbose_name_plural': 'Мемета на седмицата'},
        ),
        migrations.RemoveField(
            model_name='memeofweek',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='memeofweek',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='memeofweek',
            name='location',
        ),
        migrations.AddField(
            model_name='memeofweek',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата на качване'),
        ),
        migrations.AddField(
            model_name='memeofweek',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.meme_upload_path, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='memeofweek',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено'),
        ),
        migrations.AddField(
            model_name='memeofweek',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заглавие'),
        ),
        migrations.AlterField(
            model_name='memeofweek',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Потребител'),
        ),
    ]
