# Generated by Django 6.0 on 2025-12-22 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_memeofweek_options_remove_memeofweek_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memeofweek',
            name='voted_by',
            field=models.ManyToManyField(blank=True, related_name='voted_memes', to=settings.AUTH_USER_MODEL, verbose_name='Гласували потребители'),
        ),
        migrations.AddField(
            model_name='memeofweek',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Гласове'),
        ),
    ]
