# Generated by Django 6.0 on 2025-12-23 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_memeofweek_voted_by_memeofweek_votes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollquestion',
            options={'ordering': ['-start_date'], 'verbose_name': 'Въпрос за анкета', 'verbose_name_plural': 'Въпроси за анкети'},
        ),
        migrations.RemoveField(
            model_name='pollquestion',
            name='is_active',
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Крайна дата'),
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начална дата'),
        ),
    ]
