# Generated by Django 6.0 on 2025-12-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_pollquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentrecord',
            name='policy_version',
            field=models.CharField(default='v1.0', max_length=50),
        ),
    ]
