# Generated by Django 6.0 on 2025-12-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_consentrecord_policy_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consentrecord',
            name='analytical_accepted',
        ),
        migrations.RemoveField(
            model_name='consentrecord',
            name='marketing_accepted',
        ),
    ]
