# Generated by Django 6.0 on 2025-12-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_remove_consentrecord_analytical_accepted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Режим на поддръжка')),
            ],
            options={
                'verbose_name': 'Настройки на сайта',
                'verbose_name_plural': 'Настройки на сайта',
            },
        ),
    ]
