# Generated by Django 6.0 on 2025-12-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_bell_suggestions',
            field=models.BooleanField(default=True, verbose_name="Активирани 'Предложения за песни'"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_meme_of_the_week',
            field=models.BooleanField(default=True, verbose_name="Активирано 'Меме на седмицата'"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_weekly_poll',
            field=models.BooleanField(default=True, verbose_name="Активирана 'Седмична анкета'"),
        ),
    ]
