# Generated by Django 6.0 on 2025-12-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_sitesettings_enable_bell_suggestions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(verbose_name='Текст на известието'),
        ),
    ]
