# Generated by Django 6.0 on 2025-12-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_alter_notification_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_user_registration',
            field=models.BooleanField(default=True, verbose_name="Активирани 'Регистрации на потребители'"),
        ),
    ]
