# Generated by Django 6.0 on 2025-12-27 10:49

import blog.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_sitesettings_enable_user_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bellsongsuggestion',
            name='link',
            field=models.URLField(help_text='URL към песента в Spotify или YouTube.', max_length=2048, verbose_name='Линк към песента'),
        ),
        migrations.AlterField(
            model_name='bellsongsuggestion',
            name='note',
            field=models.TextField(blank=True, help_text='Допълнителна информация или коментар към предложението.', null=True, verbose_name='Бележка'),
        ),
        migrations.AlterField(
            model_name='bellsongsuggestion',
            name='slot',
            field=models.CharField(choices=[('start_class', 'Начало на час'), ('end_class', 'Край на час'), ('before_lunch', 'Преди голямо междучасие'), ('after_lunch', 'След голямо междучасие'), ('morning', 'Сутрешен звънец'), ('special', 'Специален повод')], default='morning', help_text='Изберете кога да звучи песента.', max_length=20, verbose_name='Кога да звучи'),
        ),
        migrations.AlterField(
            model_name='bellsongsuggestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Чакащо одобрение'), ('approved', 'Одобрено'), ('rejected', 'Отхвърлено')], default='pending', help_text='Статус на предложението (чакащо, одобрено, отхвърлено).', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='bellsongsuggestion',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и час на изпращане на предложението. Формат: YYYY-MM-DD HH:MM:SS.', verbose_name='Изпратено на'),
        ),
        migrations.AlterField(
            model_name='bellsongsuggestion',
            name='title',
            field=models.CharField(help_text='Името на песента.', max_length=255, verbose_name='Заглавие на песента'),
        ),
        migrations.AlterField(
            model_name='bellsongsuggestion',
            name='user',
            field=models.ForeignKey(help_text='Потребителят, който е направил предложението.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Потребител'),
        ),
        migrations.AlterField(
            model_name='bellsongsuggestion',
            name='voted_by',
            field=models.ManyToManyField(blank=True, help_text='Потребители, които са гласували за тази песен.', related_name='voted_songs', to=settings.AUTH_USER_MODEL, verbose_name='Гласували потребители'),
        ),
        migrations.AlterField(
            model_name='bellsongsuggestion',
            name='votes',
            field=models.IntegerField(default=0, help_text='Брой на гласовете за песента.', verbose_name='Гласове'),
        ),
        migrations.AlterField(
            model_name='category',
            name='full_name',
            field=models.CharField(help_text='Пълното име на категорията, което ще се показва на сайта.', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='short_name',
            field=models.SlugField(help_text="Кратко име в URL съвместим формат (слаг). Например: 'novini-ot-uchilishte'.", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(help_text='Съдържанието на коментара.'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и час на създаване на коментара. Формат: YYYY-MM-DD HH:MM:SS.'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(help_text='Публикацията, към която е коментарът.', on_delete=django.db.models.deletion.CASCADE, to='blog.posts'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(help_text='Потребителят, който е написал коментара.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='consent_status',
            field=models.CharField(choices=[('INFORMED', 'Информиран (Необходими)'), ('ACCEPTED', 'Приел'), ('REJECTED', 'Отказал')], help_text='Статус на даденото съгласие.', max_length=10),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='ip_address',
            field=models.CharField(blank=True, help_text='IP адрес на потребителя.', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='policy_version',
            field=models.CharField(default='v1.0', help_text='Версия на политиката за бисквитки, за която е дадено съгласието.', max_length=50),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и час на записа на съгласието. Формат: YYYY-MM-DD HH:MM:SS.'),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Потребителят, дал съгласие (ако е логнат).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='email',
            field=models.EmailField(help_text='Имейл адрес на изпращача.', max_length=254, verbose_name='Имейл'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='message',
            field=models.TextField(help_text='Съдържание на съобщението.', verbose_name='Съобщение'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='name',
            field=models.CharField(help_text='Име на изпращача.', max_length=100, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и час на изпращане. Формат: YYYY-MM-DD HH:MM:SS.', verbose_name='Изпратено на'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Потребителят, изпратил съобщението (ако е логнат).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Потребител'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees_text',
            field=models.CharField(help_text="Кой може да присъства (напр. 'Всички ученици', '8-12 клас').", max_length=255, verbose_name='Участници (текст)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(help_text="Тип на събитието (напр. 'Училищно', 'Спортно').", max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата на създаване на записа за събитието. Формат: YYYY-MM-DD HH:MM:SS.', verbose_name='Създадено на'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Подробно описание на събитието. Поддържа се Markdown.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='Кога приключва събитието (ако е приложимо). Формат: YYYY-MM-DD HH:MM:SS.', null=True, verbose_name='Крайна дата и час (по избор)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text='Къде ще се проведе събитието.', max_length=255, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=True, help_text='Отбележете, за да се показва събитието на сайта.', verbose_name='Публикувано'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(help_text='Кога започва събитието. Формат: YYYY-MM-DD HH:MM:SS.', verbose_name='Начална дата и час'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Име на събитието.', max_length=255, verbose_name='Заглавие'),
        ),
        migrations.AlterField(
            model_name='memeofweek',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и час на качване на мемето. Формат: YYYY-MM-DD HH:MM:SS.', null=True, verbose_name='Дата на качване'),
        ),
        migrations.AlterField(
            model_name='memeofweek',
            name='image',
            field=models.ImageField(blank=True, help_text='Файлът с изображението на мемето.', null=True, upload_to=blog.models.meme_upload_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='memeofweek',
            name='is_approved',
            field=models.BooleanField(default=False, help_text="Отбележете, ако мемето е одобрено за участие в 'Меме на седмицата'.", verbose_name='Одобрено'),
        ),
        migrations.AlterField(
            model_name='memeofweek',
            name='title',
            field=models.CharField(blank=True, help_text='Заглавие на мемето (по избор).', max_length=100, null=True, verbose_name='Заглавие'),
        ),
        migrations.AlterField(
            model_name='memeofweek',
            name='user',
            field=models.ForeignKey(help_text='Потребителят, който е качил мемето.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Потребител'),
        ),
        migrations.AlterField(
            model_name='memeofweek',
            name='voted_by',
            field=models.ManyToManyField(blank=True, help_text='Потребители, които са гласували за това меме.', related_name='voted_memes', to=settings.AUTH_USER_MODEL, verbose_name='Гласували потребители'),
        ),
        migrations.AlterField(
            model_name='memeofweek',
            name='votes',
            field=models.IntegerField(default=0, help_text='Брой на гласовете за мемето.', verbose_name='Гласове'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и час на създаване на известието. Формат: YYYY-MM-DD HH:MM:SS.', verbose_name='Създадено на'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Отбележете, за да активирате и покажете известието на сайта.', verbose_name='Активирано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(help_text='Съдържанието на известието, което ще се показва на потребителите.', verbose_name='Текст на известието'),
        ),
        migrations.AlterField(
            model_name='pollanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и час на отговаряне. Формат: YYYY-MM-DD HH:MM:SS.', verbose_name='Отговорено на'),
        ),
        migrations.AlterField(
            model_name='pollanswer',
            name='question',
            field=models.ForeignKey(help_text='Въпросът, на който е отговорено.', on_delete=django.db.models.deletion.CASCADE, to='blog.pollquestion', verbose_name='Въпрос'),
        ),
        migrations.AlterField(
            model_name='pollanswer',
            name='selected_option',
            field=models.ForeignKey(help_text='Опцията, която потребителят е избрал.', on_delete=django.db.models.deletion.CASCADE, to='blog.polloption', verbose_name='Избрана опция'),
        ),
        migrations.AlterField(
            model_name='pollanswer',
            name='user',
            field=models.ForeignKey(help_text='Потребителят, който е отговорил.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Потребител'),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='Отбележете, ако това е правилният отговор на въпроса.', verbose_name='Правилен отговор'),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='key',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], help_text='Буквеният ключ за тази опция (a, b, c, d).', max_length=1, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='question',
            field=models.ForeignKey(help_text='Въпросът, към който принадлежи тази опция.', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='blog.pollquestion', verbose_name='Въпрос'),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='text',
            field=models.CharField(help_text='Текстът на отговора.', max_length=255, verbose_name='Текст на опция'),
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='code',
            field=models.TextField(help_text='Код или текст на въпроса, който може да се показва на потребителите.', verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и час на създаване на анкетата. Формат: YYYY-MM-DD HH:MM:SS.', verbose_name='Създаден на'),
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и час, до които анкетата е активна. Формат: YYYY-MM-DD HH:MM:SS.', verbose_name='Крайна дата'),
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и час, от които анкетата е активна. Формат: YYYY-MM-DD HH:MM:SS.', verbose_name='Начална дата'),
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Подзаглавие на анкетата (по избор).', max_length=255, null=True, verbose_name='Подзаглавие'),
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='title',
            field=models.CharField(help_text='Заглавието на анкетата.', max_length=255, verbose_name='Заглавие'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(help_text='Файлът с изображението.', upload_to=blog.models.post_gallery_upload_path),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(help_text='Публикацията, към която е свързана тази снимка.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='allowed',
            field=models.BooleanField(default=False, help_text='Отбележете, за да одобрите публикацията за показване (за публикации, изискващи одобрение).'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(help_text='Авторът на публикацията. Полето се попълва автоматично.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='banner',
            field=models.ImageField(blank=True, help_text='Банер изображение, което ще се показва в горната част на публикацията.', null=True, upload_to=blog.models.post_banner_upload_path),
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(help_text='Категорията, към която принадлежи публикацията.', on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(help_text='Пълното съдържание на публикацията. Поддържа се Markdown формат.'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и час на създаване на публикацията. Формат: YYYY-MM-DD HH:MM:SS.'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='hook',
            field=models.TextField(help_text="Кратко въведение или 'кукичка', което да привлече вниманието на читателя.", max_length=100),
        ),
        migrations.AlterField(
            model_name='posts',
            name='published',
            field=models.BooleanField(help_text='Отбележете, ако публикацията трябва да бъде видима за всички потребители.'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(help_text='Заглавието на публикацията.', max_length=100),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=models.TextField(help_text='Пълният текст на Политиката за поверителност. Поддържа се Markdown.'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата на последната промяна. Формат: YYYY-MM-DD HH:MM:SS.'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='user',
            field=models.ForeignKey(help_text='Авторът, който е създал/редактирал политиката.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enable_bell_suggestions',
            field=models.BooleanField(default=True, help_text='Позволява на потребителите да предлагат песни за училищния звънец.', verbose_name="Активирани 'Предложения за песни'"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enable_meme_of_the_week',
            field=models.BooleanField(default=True, help_text='Позволява на потребителите да качват и гласуват за мемета.', verbose_name="Активирано 'Меме на седмицата'"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enable_user_registration',
            field=models.BooleanField(default=True, help_text='Позволява на нови потребители да се регистрират в системата.', verbose_name="Активирани 'Регистрации на потребители'"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enable_weekly_poll',
            field=models.BooleanField(default=True, help_text='Активира/деактивира показването на седмичната анкета на сайта.', verbose_name="Активирана 'Седмична анкета'"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Ако е активиран, сайтът ще показва страница за поддръжка на всички потребители, които не са администратори.', verbose_name='Режим на поддръжка'),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='content',
            field=models.TextField(help_text='Пълният текст на Условията за ползване. Поддържа се Markdown.'),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата на последната промяна. Формат: YYYY-MM-DD HH:MM:SS.'),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='user',
            field=models.ForeignKey(help_text='Авторът, който е създал/редактирал условията.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='Свързаният потребителски акаунт.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PostDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Файлът с документа (PDF, DOCX, XLSX, ZIP).', upload_to=blog.models.post_document_upload_path)),
                ('file_name', models.CharField(blank=True, help_text='По избор: потребителско име за документа.', max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Дата и час на качване на документа. Формат: YYYY-MM-DD HH:MM:SS.')),
                ('post', models.ForeignKey(help_text='Публикацията, към която е свързан този документ.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='blog.posts')),
            ],
            options={
                'verbose_name': 'Документ към публикация',
                'verbose_name_plural': 'Документи към публикации',
            },
        ),
    ]
