# Generated by Django 6.0 on 2025-12-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_alter_bellsongsuggestion_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdocument',
            name='file_name',
        ),
    ]
