# Generated by Django 6.0 on 2026-01-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_remove_postdocument_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Съдържание на промените в Markdown формат.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата на създаване.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата на последна редакция.')),
                ('is_active', models.BooleanField(default=True, help_text='Отбележете, за да се вземе предвид този запис.')),
            ],
            options={
                'verbose_name': 'Запис в дневника на промените',
                'verbose_name_plural': 'Дневник на промените',
                'ordering': ['-updated_at'],
            },
        ),
    ]
