# Generated by Django 6.0 on 2026-01-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_changelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_program_page',
            field=models.BooleanField(default=True, help_text='Показва или скрива страницата с учебната програма.', verbose_name="Активирана страница 'Програма'"),
        ),
    ]
