# Generated by Django 6.0 on 2026-01-05 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_sitesettings_enable_program_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Родителският коментар, ако този е отговор.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comments'),
        ),
    ]
