# Generated by Django 6.0 on 2026-01-09 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_sitesettings_enable_program_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Родителският коментар, ако този е отговор.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comments'),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='reason',
            field=models.CharField(choices=[('general', 'Общо запитване'), ('suggestion', 'Предложение за блога'), ('technical_issue', 'Технически проблем'), ('event_question', 'Въпрос за събитие'), ('bug_report', 'Открит бъг'), ('partnership', 'Партньорство/Сътрудничество'), ('content_concern', 'Сигнал за съдържание'), ('author_application', 'Кандидатура за автор')], default='general', help_text='Причината, поради която потребителят се свързва.', max_length=20, verbose_name='Причина за контакт'),
        ),
    ]
