# Generated by Django 6.0 on 2026-01-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_alter_comments_options_comments_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='reason',
            field=models.CharField(choices=[('general', 'Общо запитване'), ('suggestion', 'Предложение за блога'), ('technical_issue', 'Технически проблем'), ('event_question', 'Въпрос за събитие'), ('bug_report', 'Открит бъг'), ('partnership', 'Партньорство/Сътрудничество'), ('content_concern', 'Сигнал за съдържание'), ('author_application', 'Кандидатура за автор')], default='general', help_text='Причината, поради която потребителят се свързва.', max_length=20, verbose_name='Причина за контакт'),
        ),
    ]
