# Generated by Django 6.0 on 2026-01-09 21:40

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20260109_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollquestion',
            name='code',
        ),
        migrations.AddField(
            model_name='polloption',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение, което се показва с тази опция.', null=True, upload_to=blog.models.poll_media_upload_path, verbose_name='Изображение към опция'),
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение, което се показва с въпроса.', null=True, upload_to=blog.models.poll_media_upload_path, verbose_name='Изображение към въпроса'),
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='task_description',
            field=models.TextField(blank=True, default='', help_text='Текст на въпроса или описание на задачата.', verbose_name='Описание на задачата'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='reason',
            field=models.CharField(choices=[('general', 'Общо запитване'), ('suggestion', 'Предложение за блога'), ('technical_issue', 'Технически проблем'), ('event_question', 'Въпрос за събитие'), ('bug_report', 'Открит бъг'), ('partnership', 'Партньорство/Сътрудничество')], default='general', help_text='Причината, поради която потребителят се свързва.', max_length=20, verbose_name='Причина за контакт'),
        ),
    ]
